Repository OjoRise/FrontEnd, pull requests merged in 2025-06, with the labels that each got.

#26 OJORISE-27-Delete-side-scroll-bar
  src/app/globals.css
Labels: enhancement

#39 Ojorise 31 add recently recommanded component
  package-lock.json
  package.json
  src/app/main-page/page.tsx
  src/components/main-page/CompareModeToggle.tsx
  src/components/main-page/LikedPlansList.tsx
  src/components/main-page/PlanCard.tsx
  src/components/main-page/RecommendedPlanList.tsx
  src/components/main-page/SelectedPlanViewer.tsx
  src/components/page-component/MainPage.tsx
  src/components/ui/carousel.tsx
  src/stores/usePlanStore.ts
  src/types/plan.ts
Labels: enhancement

#45 OJORISE-45-add-App-Header
  public/logo.svg
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/login/success/page.tsx
  src/app/main-page/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/components/common/AppHeader.tsx
  src/components/common/ClientLayoutWrapper.tsx
  src/components/common/chatbot/ChatBotBubble.tsx
  src/components/common/chatbot/ChatBotModal.tsx
  src/components/common/progress/LinearProgress.tsx
  src/components/common/progress/LoadingLine.tsx
  src/components/common/progress/LoadingProgressCircle.tsx
  src/components/common/wrapper/ClientLayoutWrapper.tsx
  src/components/common/wrapper/ProviderWrapper.tsx
  src/components/page-component/Plan/GuestPrompt.tsx
  src/components/page-component/Plan/PlanBox.tsx
  src/components/page-component/login/LoginPage.tsx
  src/components/page-component/main-page/MainPage.tsx
  src/components/page-component/main-page/plan/GuestPlanSelector.tsx
  src/components/page-component/main-page/plan/GuestPrompt.tsx
  src/components/page-component/main-page/plan/PlanBox.tsx
  src/components/page-component/main-page/plan/PlanCombo.tsx
  src/components/page-component/main-page/plan/PlanInfoLoggedIn.tsx
  src/components/page-component/main-page/recommanded-list/CompareModeToggle.tsx
  src/components/page-component/main-page/recommanded-list/LikedPlansList.tsx
  src/components/page-component/main-page/recommanded-list/PlanCard.tsx
  src/components/page-component/main-page/recommanded-list/RecommendedPlanList.tsx
  src/components/page-component/main-page/recommanded-list/SelectedPlanViewer.tsx
  src/components/page-component/signup/SignupPage.tsx
  src/components/page-component/signup/VerticalLinearStepper.tsx
  src/components/page-component/success/SuccessPage.tsx
  src/lib/usePlanStore.ts
  src/stores/authStore.ts
  src/stores/usePlanStore.ts
  src/type/Plan.ts
  src/types/plan.ts
Labels: enhancement

#49 OJORISE-53-add-banner
  public/BannerIMG.png
  public/TongBTI.png
  src/app/page.tsx
  src/components/page-component/BannerCarousel.tsx
Labels: enhancement

#51 OJORISE-59-fix-banner-img-code
  src/components/page-component/BannerCarousel.tsx
Labels: bug

#54 OJORISE-60-fix-banner-style
  src/components/page-component/BannerCarousel.tsx
Labels: enhancement

#55 OJORISE-32-add-compare-component
  package-lock.json
  package.json
  public/decrease.svg
  public/increase.svg
  src/components/common/wrapper/ClientLayoutWrapper.tsx
  src/components/page-component/main-page/MainPage.tsx
  src/components/page-component/main-page/compare-chart/RadarChart.tsx
  src/components/page-component/main-page/compare-chart/ScrollChart.tsx
  src/components/page-component/main-page/compare-chart/TableBox.tsx
  src/stores/usePlanStore.ts
  src/utils/presentParsing.ts
Labels: enhancement

#57 OJORISE-34-add-sign-up
  src/app/globals.css
  src/components/common/ContractRadioGroup.tsx
  src/components/common/survey/DateInput.tsx
  src/components/common/survey/FamilyBundleGroup.tsx
  src/components/common/survey/FamilyNumRadioGroup.tsx
  src/components/common/survey/PlanCombo.tsx
  src/components/common/survey/PlanPrice.tsx
  src/components/common/survey/SelectCarrier.tsx
  src/components/common/survey/StepIndicator.tsx
  src/components/common/survey/StepItem.tsx
  src/components/common/survey/VerticalLinearStepper.tsx
  src/components/page-component/signup/SignupPage.tsx
  src/components/page-component/signup/VerticalLinearStepper.tsx
  src/components/page-component/success/SuccessPage.tsx
  src/services/getPlans.ts
  src/services/patchIsSurvey.ts
  src/services/postSurvey.ts
  src/stores/surveyStore.ts
  src/utils/date.ts
  tailwind.config.ts
Labels: enhancement

#65 OJORISE-63-screenshot-functions
  src/hooks/useOCRToGptMutation.ts
  src/utils/extractJsonFromGpt.ts
Labels: duplicate

#64 OJORISE-75-Banner-responsive
  src/components/page-component/main-page/plan/GuestPlanSelector.tsx
  src/components/page-component/main-page/plan/GuestPrompt.tsx
  src/components/page-component/main-page/plan/PlanInfoLoggedIn.tsx
Labels: enhancement

#70 OJORISE-81-manage-token
  src/components/common/AppHeader.tsx
  src/components/common/wrapper/ClientLayoutWrapper.tsx
  src/components/page-component/main-page/MainPage.tsx
  src/components/page-component/main-page/compare-plans/LikedPlansList.tsx
  src/components/page-component/main-page/plan/GuestPrompt.tsx
  src/components/page-component/main-page/plan/PlanBox.tsx
  src/components/page-component/success/SuccessPage.tsx
  src/hooks/useGetIsSurveyed.ts
  src/hooks/useRefreshToken.ts
  src/hooks/useSurveyMutation.ts
  src/hooks/useWithdraw.ts
  src/lib/auth.ts
  src/lib/axios.ts
  src/prompt/OCRPrompt.ts
  src/services/auth.ts
  src/services/deleteWithdraw.ts
  src/services/initialSetting.ts
  src/stores/authStore.ts
Labels: enhancement

#66 OJORISE-79-Banner-responsive
  src/components/page-component/BannerCarousel.tsx
Labels: enhancement

#67 OJORISE-80-add-footer-section
  src/components/common/Footer.tsx
  src/components/common/wrapper/ClientLayoutWrapper.tsx
Labels: enhancement

#72 OJORISE-91-fix-build-error
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/git-push.yml
  src/components/common/chatbot/ChatBotModal.tsx
  src/components/common/wrapper/ClientLayoutWrapper.tsx
  src/types/OCR.ts
  src/types/UserProfile.ts
  src/types/ocr.ts
Labels: bug

#74 OJORISE-88-feat-logout
  src/components/common/AppHeader.tsx
  src/hooks/useLogout.ts
  src/services/auth.ts
Labels: enhancement

#75 Ojorise 93 fix fetch 401 error resolve
  src/components/common/AppHeader.tsx
  src/components/page-component/main-page/MainPage.tsx
  src/components/page-component/success/SuccessPage.tsx
Labels: enhancement

#78 OJORISE-94-Fix-Banner-responsive
  src/components/page-component/BannerCarousel.tsx
Labels: enhancement

#85 OJORISE-87-add-chart
  package-lock.json
  src/components/common/chatbot/ChatBotBubble.tsx
  src/components/common/chatbot/ChatBotModal.tsx
  src/components/common/survey/PlanCombo.tsx
  src/components/common/survey/SelectCarrier.tsx
  src/components/common/survey/VerticalLinearStepper.tsx
  src/components/common/wrapper/ClientLayoutWrapper.tsx
  src/components/page-component/main-page/compare-chart/RadarChart.tsx
  src/components/page-component/main-page/compare-chart/TableBox.tsx
  src/components/page-component/main-page/compare-chart/comparePlan.ts
  src/components/page-component/main-page/compare-plans/PlanCard.tsx
  src/components/page-component/main-page/compare-plans/SelectedPlanViewer.tsx
  src/components/page-component/main-page/plan/GuestPlanSelector.tsx
  src/components/page-component/main-page/plan/PlanBox.tsx
  src/components/page-component/main-page/plan/PlanInfoLoggedIn.tsx
  src/components/page-component/success/SuccessPage.tsx
  src/components/page-component/tongbti/result/ResultPage.tsx
  src/hooks/useGetMyPlan.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useSurvey.ts
  src/lib/axios.ts
  src/services/auth.ts
  src/services/browsePlan.ts
  src/services/chatWithGPT.ts
  src/services/dipPlanService.ts
  src/services/initialSetting.ts
  src/services/myPlan.ts
  src/services/ocr.ts
  src/services/planAge.ts
  src/services/recommenendPlanService.ts
  src/services/survey.ts
  src/services/tongbti.ts
  src/stores/authStore.ts
  src/stores/myPlanStore.ts
  src/stores/usePlanStore.ts
  src/types/plan.ts
  src/types/survey.ts
  src/utils/numberParsing.ts
  src/utils/presentParsing.ts
Labels: enhancement

#83 OJORISE-98-fix-footer-design
  src/components/common/Footer.tsx
Labels: enhancement

#86 OJORISE-108-fix-App-Header-Desing
  public/kakaologinBtn.png
  src/components/common/AppHeader.tsx
Labels: enhancement

#89 OJORISE-110-Fix-Banner-style
  public/nextBtn.png
  public/prevBtn.png
  src/components/page-component/main-page/BannerCarousel.tsx
Labels: enhancement

#93 OJORISE-121-fix-chatbot-ui
  public/chatbot.svg
  src/app/globals.css
  src/components/common/chatbot/ChatBotBubble.tsx
  src/components/common/chatbot/ChatBotModal.tsx
  src/components/common/progress/LoadingLine.tsx
  src/components/ui/scroll-area.tsx
Labels: enhancement

#94 OJORISE-124-fix-chatbot-ui
  src/app/globals.css
  src/components/common/chatbot/ChatBotBubble.tsx
  src/components/common/chatbot/ChatBotModal.tsx
  src/components/ui/scroll-area.tsx
Labels: enhancement

#98 Ojorise 123 fix skeleton shows when not logged in
  src/components/common/chatbot/ChatBotModal.tsx
  src/components/page-component/main-page/compare-plans/LikedPlansList.tsx
  src/components/page-component/main-page/compare-plans/RecommendedPlanList.tsx
  src/components/page-component/success/SuccessPage.tsx
  src/components/page-component/test-age-page/result/AgeTestResult.tsx
  src/components/page-component/tongbti/LoadingPage.tsx
  src/hooks/useAuthStoreRehydrated.ts
  src/hooks/useLikedPlans.ts
  src/hooks/useRecommendedPlans.ts
  src/lib/recommendationStorage.ts
  src/services/initialSetting.ts
  src/stores/authStore.ts
  src/stores/chatBotStore.ts
  src/stores/usePlanStore.ts
Labels: enhancement

#101 OJORISE-132 fix ocr api and chatbot modal
  src/components/common/chatbot/ChatBotModal.tsx
  src/services/ocr.ts
Labels: bug, enhancement

#105 OJORISE-131-fix-token
  src/components/common/wrapper/ClientLayoutWrapper.tsx
  src/components/page-component/edit-survey/EditSurveyPage.tsx
  src/components/page-component/main-page/plan/PlanBox.tsx
  src/components/page-component/main-page/plan/PlanInfo.tsx
  src/components/page-component/mypage/MyPage.tsx
  src/components/page-component/success/SuccessPage.tsx
  src/hooks/useGetMyPlan.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/usePlanAge.ts
  src/hooks/useRefreshToken.ts
  src/hooks/useSurvey.ts
  src/hooks/useSurveyResult.ts
  src/hooks/useTongBTI.ts
  src/prompt/ageTestPrompt.ts
Labels: bug

#107 OJORISE-149-FIX: fixed appheader style
  src/components/common/AppHeader.tsx
  src/components/common/OffCanvas.tsx
Labels: enhancement

#111 Ojorise 129 fix tongbti UI
  public/TongBTI/questionIcon.png
  public/kakaoButton.png
  public/linkButton.png
  src/components/common/button/ShareButton.tsx
  src/components/page-component/main-page/MainPage.tsx
  src/components/page-component/main-page/compare-plans/CompareModeToggle.tsx
  src/components/page-component/main-page/compare-plans/LikedPlansList.tsx
  src/components/page-component/main-page/compare-plans/RecommendedPlanList.tsx
  src/components/page-component/main-page/compare-plans/SelectedPlanViewer.tsx
  src/components/page-component/tongbti/LoadingPage.tsx
  src/components/page-component/tongbti/QuestionCard.tsx
  src/components/page-component/tongbti/TongBTIPage.tsx
  src/components/page-component/tongbti/result/ResultPage.tsx
  src/types/tongBTI.ts
Labels: enhancement

#112 OJORISE-157 add plancard URL
  src/components/page-component/main-page/compare-plans/PlanCard.tsx
  src/types/plan.ts
Labels: enhancement

#126 OJORISE-154-fix-detail-ui
  src/components/page-component/main-page/MainPage.tsx
  src/components/page-component/main-page/compare-chart/ScrollChart.tsx
  src/components/page-component/main-page/compare-plans/LikedPlansList.tsx
  src/components/page-component/main-page/compare-plans/RecommendedPlanList.tsx
  src/components/page-component/main-page/plan/GuestPrompt.tsx
  src/components/page-component/signup/PopoverBox.tsx
Labels: duplicate

#137 OJORISE-176 fix chatbot modal
  src/components/common/chatbot/ChatBotModal.tsx
Labels: enhancement
